version: '3.9'

services:
  birdappbase:
    image: mongo:latest
    container_name: "geotripbase"
    ports:
      - 27017:27017

  keyclock:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keyclock_geoTrip
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-config.json
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped

#  birdappservice:
#    image: birdapp:latest
#    container_name: "birdappservice"
#    ports:
#      - 8080:8080
#    links:
#      - birdappbase

