spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: GeoTrip
      host: localhost
      port: 27017

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/realm_geo
          jwk-set-uri: http://localhost:9090/realms/realm_geo/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: geo
      principle-attribute: preferred_username

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui-custom.html